-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-09-27T13:36:37.256Z

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "email_verified_at" timestamp,
  "password" varchar(255) NOT NULL,
  "remember_token" varchar(100),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "password_reset_tokens" (
  "email" varchar(255) PRIMARY KEY,
  "token" varchar(255) NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "sessions" (
  "id" varchar(255) PRIMARY KEY,
  "user_id" bigint,
  "ip_address" varchar(45),
  "user_agent" text,
  "payload" longtext NOT NULL,
  "last_activity" integer NOT NULL
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "slug" varchar(120) UNIQUE NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  "title" varchar(255) NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL,
  "content" text NOT NULL,
  "status" varchar(20) DEFAULT 'draft',
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE INDEX ON "sessions" ("user_id");

CREATE INDEX ON "sessions" ("last_activity");

CREATE INDEX ON "posts" ("slug");

CREATE INDEX ON "posts" ("user_id", "status");

COMMENT ON TABLE "users" IS 'Tabel pengguna bawaan Laravel';

COMMENT ON TABLE "password_reset_tokens" IS 'Token untuk reset password';

COMMENT ON COLUMN "posts"."user_id" IS 'Foreign key ke users.id';

COMMENT ON COLUMN "posts"."category_id" IS 'Foreign key ke categories.id';

COMMENT ON COLUMN "posts"."status" IS 'draft | published | archived';

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
